### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by supriyopaul** [deep-compute/logagg#42]
1. The beginning should be simple. Should not scare users with how to change nginx configuration and all.
2. README should showcase the uniform format we put the logs in.. and why we choose to do so? e.g. Uuid field in the records.
3. User should experience the collector run with minimum efforts put in, like without putting nsq up. May be provide sample log files and print the parsed logs on the screen rather than sending to nsq.

**Comment by supriyopaul** [comment]
Uniform format we put the logs in:

id (str) - A unique id per log with time ordering. Useful to avoid storing duplicates.
timestamp (str) - ISO Format time. eg: <FIXME>
data (dict) - Parsed log data
raw (str) - Raw log line read from the log file
host (str) - hostname of the node where this log was generated
handler (str) - name of the collect handler that processed the raw log line
file (str) - full path of the file in the host where this log line came from
type (str) - One of "log", "metric" (Is there one more type?) 

error (bool) - True if collection handler failed during processing
error_tb (str) - Error traceback

**Comment by vasudhaellina** [comment]
Don’t we need to add Error Severity level as part of above and maybe some sort of message code?

**Comment by supriyopaul** [comment]
https://github.com/deep-compute/logagg/pull/62

**Comment by supriyopaul** [comment]
https://github.com/deep-compute/logagg/pull/62
