### ISSUE TITLE
Parsers for Infuxdb 

### ISSUE THREAD

**Issue by supriyopaul** [deep-compute/logagg#56]
1. Understand Influxdb line protocol?
2. How does forwarder decide if a line is a metric or a log? issue #55 
3. What fields get indexed?

**Comment by supriyopaul** [comment]
![image](https://user-images.githubusercontent.com/33823698/37154946-91f28e24-2307-11e8-8dfa-7cdbab658901.png)
![image](https://user-images.githubusercontent.com/33823698/37154967-a0d9c10a-2307-11e8-9745-6b933c5e2bcb.png)

**Comment by supriyopaul** [comment]
Sample parser results for Basescript serverstats:
![image](https://user-images.githubusercontent.com/33823698/37156119-2fe0d1b0-230b-11e8-985f-49ede9a87923.png)

**Comment by supriyopaul** [comment]
@prashanthellina  can you confirm the final output please?

**Comment by prashanthellina** [comment]
@supriyopaul Looks good! Thank you.
