### ISSUE TITLE
#Errors: client facing Logagg errors.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/logagg#63]
@supriyopaul 
* While using `logagg` module we facing some probelms.
* We are facing some issue of using your mongodb readme so can you modify it please.
#### problem-1
* We are getting error at logagg-forwarder level
![screen shot 2018-03-07 at 12 10 44 pm](https://user-images.githubusercontent.com/16955073/37077589-9827d440-2201-11e8-8371-749e6aea66ae.png)
#### Problem-2
* We are not getting records to Mongo-db.
![screen shot 2018-03-07 at 12 10 01 pm](https://user-images.githubusercontent.com/16955073/37077621-b73f14a6-2201-11e8-8ac2-ac2a402e117f.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* If we got an error while handling a message in `logagg` not that log message at some location it can help us while debugging `logagg` errors.

**Comment by Rajendra-R** [comment]
@supriyopaul 
* We are getting `Type Error` while processing the `mongo-db` log because in mongo record ,we are having `ObjectID(121sfsdf)` we know that id is generated by `mongo-db` instead of that take the `id` from log message and put at a higher level.
![screen shot 2018-03-07 at 3 43 50 pm](https://user-images.githubusercontent.com/16955073/37090194-63525326-2229-11e8-9146-bf4e2a48b11a.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* While parsing docker log using `basescript` handler in `logagg-collector` we getting error while handling log line.
#### Error:
![screen shot 2018-03-07 at 7 44 56 pm](https://user-images.githubusercontent.com/16955073/37097091-99732662-2240-11e8-869a-aed82be15cff.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* We found one typo mistake in the Readme file in `logagg-forwarder`, we have different handlers to format logs in readme you provided a handler called `docker_file_log_driver` but the actual name was `docker_log_file_driver`

**ReadMe:**
![screen shot 2018-03-08 at 10 10 43 am](https://user-images.githubusercontent.com/16955073/37133518-cc58f970-22b9-11e8-9e60-dc577812a5c8.png)

**Refer:** https://github.com/deep-compute/logagg/blob/5ea523f48fc343c4eb9a02abc3c7f1c8c8ed05d6/logagg/formatters.py#L8

**Comment by supriyopaul** [comment]
**Problem 1** is due to records containing keys which are against MongoDB line protocol. We'll make a parser for records getting into MongoDB. To remove all the '.' from the keys and replacing it with '_'
**Problem 2** is because of error while inserting into MongoDB the whole forwarder stops. We'll make it move on after logging the records that were not inserted.
**Problem 3** formatter error when docker_log_file_driver containing Basescript logs are passed to logagg.formatters.basecript.I tested it, and it worked earlier. I'll test it again.
**Problem 4** I'll fix the README.md but I think we should rather change the name it's confusing :P

**Comment by Rajendra-R** [comment]
@supriyopaul 
* We are writing all docker logs to separate directory using `--log-driver file-log-driver` every day it was creating a new `log` file with the respective date the `logagg collector` was not able to read the new file right I am not sure if it is a backup file like `log` module then it's ok if not, we have to consider this issue.
![screen shot 2018-03-08 at 4 31 45 pm](https://user-images.githubusercontent.com/16955073/37148040-01be19c6-22ef-11e8-98cb-3c37e68017cd.png)

**Comment by supriyopaul** [comment]
@Rajendra-R  can u show me a `ls -lhrt`, just to make sure log file didn't reach it's default limit i.e. 10MB.

**Comment by supriyopaul** [comment]
@Rajendra-R  docker-file-log-driver is writing to the same file all other files are backups
![image](https://user-images.githubusercontent.com/33823698/37150484-d72c10d8-22f7-11e8-819f-d618af01f498.png)

**Comment by supriyopaul** [comment]
@Rajendra-R  please create different issues for different bugs/questions It's hard to track all at one place
