### ISSUE TITLE
#Errors: logagg_forwarder errors.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/logagg#67]
@supriyopaul 
* While running the `logagg_forwarder` we got an error.
#### Errors:
![screen shot 2018-03-12 at 1 06 01 pm](https://user-images.githubusercontent.com/16955073/37271061-58040eb6-25f7-11e8-972b-c9bddf4f8037.png)
![screen shot 2018-03-12 at 11 35 10 am](https://user-images.githubusercontent.com/16955073/37271062-582fb098-25f7-11e8-9258-ffc4c4d6fcbd.png)
* Due to this error, we observed that sometimes NSQ connection is gone at `logagg-forwarder` you can check below.
![screen shot 2018-03-12 at 12 31 26 pm](https://user-images.githubusercontent.com/16955073/37271151-b7b7ad2c-25f7-11e8-9dbc-580b1accc536.png)
* Because of all these issues we have a `huge delay` of writing logs to mongodb.
![screen shot 2018-03-12 at 12 28 31 pm](https://user-images.githubusercontent.com/16955073/37271211-e7e77716-25f7-11e8-8f52-712fb11d7cb3.png)
![screen shot 2018-03-12 at 12 29 03 pm](https://user-images.githubusercontent.com/16955073/37271213-e811e1c2-25f7-11e8-8ce9-724778093831.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* After modifying the `max-values-per-tag=0` that error was gone and we got a new error called `max-series-per-database` shown given below.
**Error:** 
![screen shot 2018-03-12 at 2 43 39 pm](https://user-images.githubusercontent.com/16955073/37275126-6018b3f6-2604-11e8-80db-b9a0c2ef8a2a.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* After modifying the `max-series-per-database=0` in the influxdb.conf file the error is resolved.

**Comment by Rajendra-R** [comment]
@supriyopaul 
* In `logagg-collector` we are facing an error while handling the log line.
#### Error:
![screen shot 2018-03-12 at 2 57 39 pm](https://user-images.githubusercontent.com/16955073/37276700-8628df68-2608-11e8-8417-086e3497b943.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* We got `BulkWriteError` to mongodb in `logag-forwarder`
#### Error:
![screen shot 2018-03-12 at 3 29 52 pm](https://user-images.githubusercontent.com/16955073/37280322-71675cb6-2613-11e8-8aa1-0ed402dc9d72.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* We observed that there was a `huge_delay` of messages, stored in `mongodb` it has 10 times slower than log file producer.
![screen shot 2018-03-12 at 4 58 53 pm](https://user-images.githubusercontent.com/16955073/37281327-aed5e448-2616-11e8-8b74-b639191c5264.png)
![screen shot 2018-03-12 at 4 59 14 pm](https://user-images.githubusercontent.com/16955073/37281347-bc3dc2ea-2616-11e8-9981-4805248fcb5c.png)

**Comment by supriyopaul** [comment]
@Rajendra-R we are measuring and optimizing the the performance of logagg collector & forwarder in #69

**Comment by Rajendra-R** [comment]
@supriyopaul 
#### Update:
* We modified the `influxdb` config file changes `max-series-per-database=0` and `max-values-per-tag=0` right we did this because of error we faced, as per @prashanthellina discussion we don't modify the default arguments, because it may cause performance issue.

**Comment by Rajendra-R** [comment]
@supriyopaul 
* While running `logagg-forwarder`, we are getting these errors. Can you please check and let me know.
#### Error-1
![screen shot 2018-03-21 at 5 06 12 pm](https://user-images.githubusercontent.com/16955073/37708261-ee36a584-2d2b-11e8-943a-93a0f3019e5f.png)
#### Error-2
![screen shot 2018-03-21 at 10 51 10 am](https://user-images.githubusercontent.com/16955073/37708276-0433aa9e-2d2c-11e8-96fc-0c0ae6148e4f.png)

**Comment by supriyopaul** [comment]
@Rajendra-R That was Influxdb's and mongodb's errors. MongoDB, may be due to duplicate records. InfluxDB may be because of violating the line protocol.
