### ISSUE TITLE
#Errors: logagg_collector errors.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/logagg#68]
@supriyopaul 
* In `logagg-collector` we are facing an error while handling the log line.
#### Error:
![screen shot 2018-03-12 at 2 57 39 pm](https://user-images.githubusercontent.com/16955073/37276700-8628df68-2608-11e8-8417-086e3497b943.png)

**Comment by supriyopaul** [comment]
suppose it was a broken log line of some sort..! 
![image](https://user-images.githubusercontent.com/33823698/37383814-1163a766-2771-11e8-9fdd-495b171fd54c.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* I think this bad reading was happened by `logagg` because we didn't have a bad log in our log file.

**Comment by Rajendra-R** [comment]
#### Status-Update:
@supriyopaul 
* After increasing the performance of `logagg-collector` the maximum speed was `5000/sec` but after testing I didn't reach that much speed I got approx `1400/sec` for `0.1Million` records it took `74 sec` which means `1351 rec/sec`
![screen shot 2018-03-21 at 3 37 29 pm](https://user-images.githubusercontent.com/16955073/37704390-a864c87c-2d1e-11e8-8e45-6f83820493aa.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* While running the `logagg-collector` we are getting `connection-error` can you please consider this as high-priority.
![screen shot 2018-03-22 at 10 40 10 am](https://user-images.githubusercontent.com/16955073/37752328-9b0b7cbc-2dbd-11e8-85c3-4cd9f4af4e19.png)

**Comment by Rajendra-R** [comment]
@supriyopaul 
* Finally the bugs were resolved, it's working fine for now:stuck_out_tongue:.
* Now I can see metrics on a Dashboard.
![screen shot 2018-03-22 at 6 07 46 pm](https://user-images.githubusercontent.com/16955073/37770987-299dc3a2-2dfc-11e8-85b7-f1c850b2e510.png)

**Comment by supriyopaul** [comment]
Can u please review https://github.com/deep-compute/logagg/pull/74 or use the present code in my repository https://github.com/supriyopaul/logagg/tree/bug_fixes and close this issue @Rajendra-R
