### ISSUE TITLE
#Feature: Make particular string as a `field` instead of `tag`.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/logagg#79]
#### Read-Me:
@supriyopaul 
* Initially if there was a string the `logagg` is deciding it as a `tag` but we have a `tag` limit in `influxdb` as `100000` if we reach that limit it causes an error.
Refer: https://docs.influxdata.com/influxdb/v1.3/administration/config/#max-values-per-tag-100000
![screen shot 2018-04-16 at 11 48 06 am](https://user-images.githubusercontent.com/16955073/38792711-1238a9ce-416c-11e8-8a11-ba0742245764.png)
* In our case we have a key called `session_id` the value should be string if we ran more sources it will generate more unique_id so it causes an issue in future with `influxdb` so we know that there is no limit for `fields` so we want a feature like we have to make string as field instead of `tag`.

**Comment by supriyopaul** [comment]
'_key' == Stored as string
'__key' == Not stored at all
