### ISSUE TITLE
Notifications on error logs.

### ISSUE THREAD

**Issue by RamanjaneyuluIdavalapati** [deep-compute/logagg#84]
- Is there any feature such that I can get notified (ex: through email) when error logs are coming. If not is there any plan to implement.
- This is needed because in production if I get the notification then I can quickly go and fix the bug.

**Comment by supriyopaul** [comment]
@RamanjaneyuluIdavalapati  the feature you are asking for is basically the one that should be supported by the database / Alerting system. Logagg has a clear goal of efficiently collecting logs which we are extending towards  collecting & efficiently exposing the collected logs to the user. Alerting is basically build over it, and very specific to users use-case.
There are tools that do it better than anyone e.g. Grafana, But It doesn't have support for MOngoDB as a datasource. But All grafana does is continuously query the database and fetch the results, display it. You could write your own Grafana for MongoDB, i.e. a script using pymongo that queries the database for a user specified condition regularly and notifies you if records are found.

**Comment by supriyopaul** [comment]
I will provide you with an example:
Our goal is to list the new records in a query like:
![image](https://user-images.githubusercontent.com/33823698/42149253-141f527e-7df3-11e8-9f36-46ea52b3b81b.png)

**Comment by jaswanth098** [comment]
This is no relevant to logagg closing this
